apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: random-tvshow-argo-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/sundarsudandiraraj/random-tvshow-cd.git'
    path: .k8s
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: nextjs
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true